### ISSUE TITLE
Versions of dependencies

### ISSUE THREAD

**Issue by kkirtac** [ahsaniqbal/Kinetics-FeatureExtractor#1]
Hi @ahsaniqbal ,

thanks for your work. There are lots of dependencies and they are kind of older. Could you please specify the exact versions of the dependencies, like you did for boost?

CUDA, CuDnn, Tensorflow, Sonnet.

It would be great to receive a dockerfile from you, as it is painful to connect all dependencies and make it work.

Best,

EDIT: I have installed `tensorflow-gpu==1.2` and `dm-sonnet-gpu==1.1` but have problems with python version 2.7 in my docker container:

```
pip show tensorflow
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: Package(s) not found: tensorflow
```

Could you provide a recipe on how I can build things using python3?

**Comment by ahsaniqbal** [comment]
Not an issue
