### ISSUE TITLE
how to get the code working 

### ISSUE THREAD

**Issue by khaled26** [ahsaniqbal/Kinetics-FeatureExtractor#2]
hello , 
thanks for sharing this intersting code. 
can you please share more details how i can get it working ? 
i am using google colab to run it .. can you explain how i can build CPPinterface.cpp file ? 
is there any detailed doc ? or a video that explain step by step ? 

thank you

**Comment by ahsaniqbal** [comment]
Detailed instructions for building CPPinterface.cpp are provided in README. I haven't tested on google colab.
