### ISSUE TITLE
ImportError: No module named i3d

### ISSUE THREAD

**Issue by khaled26** [ahsaniqbal/Kinetics-FeatureExtractor#5]
Hey @ahsaniqbal  , 
i got all the Dependencies, i am getting a message of ImportError: No module named i3d 
i have cloned  https://github.com/deepmind/kinetics-i3d into my Kinetics-FeatureExtractor project.
is there more steps to do ? how i can configure it ? 

![image](https://user-images.githubusercontent.com/9578089/115484346-57946a00-a25b-11eb-9875-bfd8d905a216.png)

thanks

**Comment by ahsaniqbal** [comment]
Hey,

Please follow read me. "it expects i3d.py (kinetics-i3d model code) in the same directory".

Regards

**Comment by khaled26** [comment]
thanks for responding . 
i am getting a strange error , stucked with it long time ago .. it's related to 'begin' module ,  have you any idea? 
![image](https://user-images.githubusercontent.com/9578089/115638927-04ceb700-a31c-11eb-8a86-5ec04db7928a.png)
